version: 0.2

phases:
  install:
   runtime-versions:
     java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - ./mvnw package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - codedeploy/**/*
    - systemd/*
    - scripts/start.sh
cache:
  paths:
    # $HOME is always /root per https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html
    - '/root/.m2/**/*'