version: 0.2

phases:
  install:
   runtime-versions:
     java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - ./mvnw package
      - "ls -l $HOME/.m2/repository || :"
      - "ls -l /.m2/repository || :"
      - "ls -l .m2/repository || :"
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - codedeploy/**/*
    - systemd/*