resources:
- deployment.yaml
- service.yaml
- ingress.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: spring-petclinic
    path: image.patch.yaml